version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    ports:
      - "5900:5900"  # Expose VNC port for Chrome
    depends_on:
      - selenium-hub
    environment:
      - BROWSER=chrome
      - HUB_HOST=selenium-hub

  firefox:
    build:
      context: .
      dockerfile: Dockerfile.firefox
    ports:
      - "5901:5900"  # Expose VNC port for Firefox
    depends_on:
      - selenium-hub
    environment:
      - BROWSER=firefox
      - HUB_HOST=selenium-hub

  firefox-headless:
    build:
      context: .
      dockerfile: Dockerfile.headless
    depends_on:
      - selenium-hub
    environment:
      - BROWSER=headless
      - HUB_HOST=selenium-hub
